diplom/chat/urls.py
# chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.chat, name='chat'),
    path('<str:room_name>/', views.room, name='room'),
]

diplom/diplom/urls.py
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.urls import path, include

from diplom import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('my_profile/', include('myprofile.urls')),
    path('chat/', include('chat.urls')),
]
if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

diplom/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login/', views.loging, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('registr/', views.registr_user, name='registr'),
    path('save/', views.save_data, name='save_data'),
    path('gaz/', views.gaz, name='gaz'),
    path('svet/', views.svet, name='svet'),
    path('voda/', views.voda, name='voda'),
]

diplom/myprofile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.my_profile, name='my_profile'),
    path('get_user_id/', views.get_user_id, name='get_user_id'),
]

diplom/main/models.py
from django.db import models
from django.utils import timezone


class Services(models.Model):
    UTILITY_CHOICES = [
        ('gas', 'газ'),
        ('svet', 'свет'),
        ('voda', 'вода'),
    ]

    account_number = models.CharField(max_length=100)
    tariff = models.DecimalField(max_digits=6, decimal_places=2)
    meter_reading = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(default=timezone.now)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    utility_type = models.CharField(max_length=20, choices=UTILITY_CHOICES)
    user_id = models.IntegerField()

    def __str__(self):
        return f'Услуга: {self.utility_type} {self.account_number}'

diplom/myprofile/models.py
from django.contrib.auth.models import User
from django.db import models


# Модель профайла пользователя
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    surname = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    patronymic = models.CharField(max_length=100)
    email = models.EmailField()
    avatar = models.ImageField(upload_to='avatars/')
    birth_date = models.DateField(null=True, default=None)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    house_number = models.CharField(max_length=20)
    apartment_number = models.CharField(max_length=20)

    class Meta:
        verbose_name='Профиль'
        verbose_name_plural='Профиль'

    def __str__(self):
        return f"{self.surname} {self.name} {self.patronymic}"

diplom/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Services


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['username'].label = ""
        self.fields['email'].label = ""
        self.fields['password1'].label = ""
        self.fields['password2'].label = ""
        self.fields['username'].widget.attrs.update(
            {'class': 'form-item form-control'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-item form-control'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-item form-control'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-item form-control'})

        # giving place holders to fields
        self.fields['username'].widget.attrs.update(
            {'placeholder': 'Имя пользователя*'})
        self.fields['email'].widget.attrs.update(
            {'placeholder': 'E-mail*'})
        self.fields['password1'].widget.attrs.update(
            {'placeholder': 'Пароль*'})
        self.fields['password2'].widget.attrs.update(
            {'placeholder': 'Повторите пароль*'})

        for text in ['username', 'password1', 'password2']:
            self.fields[text].help_text = None

diplom/myprofile/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
        labels = {
            'surname': 'Фамилия',
            'name': 'Имя',
            'patronymic': 'Отчество',
            'email': 'Эл. почта',
            'avatar': 'Аватар',
            'birth_date': 'Дата рождения',
            'phone': 'Телефон',
            'city': 'Город',
            'street': 'Улица',
            'house_number': 'Дом',
            'apartment_number': 'Квартира',
        }

diplom/main/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, LoginForm
from django.contrib import messages

from django.http import JsonResponse, HttpResponse

from .models import Services
from django.contrib.auth.models import User
from django.utils import timezone
import json


# Create your views here.
def index(request):
    return render(request, 'main/index.html')


def about(request):
    return render(request, 'main/about.html')


def loging(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("index")
        else:
            return redirect("loging")
    else:
        return render(request, "main/login.html")


def logout_user(request):
    logout(request)
    return redirect("login")


def registr_user(request):
    form = SignUpForm()

    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("index")
    return render(request, "main/registr.html", {"form": form})


def save_data(request):
    if request.method == 'POST':
        account_number = request.POST.get('account_number')
        tariff = request.POST.get('tariff')
        meter_reading = request.POST.get('meter_reading')
        total_cost = request.POST.get('total_cost')
        utility_type = request.POST.get('utility_type')
        user_id = request.POST.get('user_id')
        print(utility_type)

        # Проверка, что tariff и meter_reading являются числами
        try:
            tariff = float(tariff)
            meter_reading = float(meter_reading)
        except ValueError:
            return JsonResponse(
                {'error': 'Tariff and meter reading must be numeric'},
                status=400)

        # логика для сохранения данных в базу данных
        Services.objects.create(
            account_number=account_number,
            tariff=tariff,
            meter_reading=meter_reading,
            total_cost=total_cost,
            utility_type=utility_type,
            user_id=user_id)

        return JsonResponse({'message': 'Data saved successfully'})
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=405)


def gaz(request):
    # Получаем user_id, например, из запроса
    user_id = request.user.id

    # Уточняем тип услуги (в вашем случае, 'gaz')
    utility_type = 'gas'

    # Получение последних 12 записей из таблицы Services для данного пользователя и данной услуги
    last_12_services = Services.objects.filter(user_id=user_id,
                                               utility_type=utility_type).order_by(
        '-id')[:12]

    # Получение последнего показания газа из базы данных 
    last_meter_reading = Services.objects.filter(user_id=user_id,
                                                 utility_type=utility_type).order_by(
        '-id').first().meter_reading if Services.objects.filter(
        user_id=user_id, utility_type=utility_type).exists() else 0

    last_meter_reading = float(last_meter_reading)
    # Сумма к оплате
    last_total_cost = Services.objects.filter(user_id=user_id,
                                                 utility_type=utility_type).order_by(
        '-id').first().total_cost if Services.objects.filter(
        user_id=user_id, utility_type=utility_type).exists() else 0

    last_total_cost = float(last_total_cost)

    # Подготавливаем контекст для передачи данных на страницу
    context = {
        'last_meter_reading': json.dumps(
            last_meter_reading) if last_meter_reading is not None else None,
        'last_12_services': last_12_services,
        'utility_type': utility_type,
        'last_total_cost': last_total_cost,
        'user_id': user_id,
        # Другие данные, которые вы хотите передать на страницу
    }

    # Рендерим страницу gaz.html с передачей контекста
    return render(request, 'main/gaz.html', context)


def svet(request):
    # Получаем user_id, например, из запроса
    user_id = request.user.id

    # Уточняем тип услуги (в вашем случае, 'svet')
    utility_type = 'svet'

    # Получение последних 12 записей из таблицы Services для данного пользователя и данной услуги
    last_12_services = Services.objects.filter(user_id=user_id,
                                               utility_type=utility_type).order_by(
        '-id')[:12]

    # Получение последнего показания газа из базы данных
    last_meter_reading = Services.objects.filter(user_id=user_id,
                                                 utility_type=utility_type).order_by(
        '-id').first().meter_reading if Services.objects.filter(
        user_id=user_id, utility_type=utility_type).exists() else 0

    last_meter_reading = float(last_meter_reading)

    # Подготавливаем контекст для передачи данных на страницу
    context = {
        'last_meter_reading': json.dumps(
            last_meter_reading) if last_meter_reading is not None else None,
        'last_12_services': last_12_services,
        'utility_type': utility_type,
        'user_id': user_id,
        # Другие данные, которые вы хотите передать на страницу
    }

    # Рендерим страницу gaz.html с передачей контекста
    return render(request, 'main/svet.html', context)


def voda(request):
    # Получаем user_id, например, из запроса
    user_id = request.user.id

    # Уточняем тип услуги (в вашем случае, 'svet')
    utility_type = 'voda'

    # Получение последних 12 записей из таблицы Services для данного пользователя и данной услуги
    last_12_services = Services.objects.filter(user_id=user_id,
                                               utility_type=utility_type).order_by(
        '-id')[:12]

    # Получение последнего показания газа из базы данных
    last_meter_reading = Services.objects.filter(user_id=user_id,
                                                 utility_type=utility_type).order_by(
        '-id').first().meter_reading if Services.objects.filter(
        user_id=user_id, utility_type=utility_type).exists() else 0

    last_meter_reading = float(last_meter_reading)

    # Подготавливаем контекст для передачи данных на страницу
    context = {
        'last_meter_reading': json.dumps(
            last_meter_reading) if last_meter_reading is not None else None,
        'last_12_services': last_12_services,
        'utility_type': utility_type,
        'user_id': user_id,
        # Другие данные, которые вы хотите передать на страницу
    }

    # Рендерим страницу gaz.html с передачей контекста
    return render(request, 'main/voda.html', context)

diplom/myprofile/views.py
from django.shortcuts import render, redirect
from .models import Profile
from .forms import ProfileForm
from django.http import JsonResponse


def my_profile(request):
    user = request.user
    profile, created = Profile.objects.get_or_create(user=user, defaults={
        'surname': user.last_name,
        'name': user.first_name,
        'patronymic': '',
        'email': user.email,
        'avatar': '',
        'birth_date': None,
        'phone': '',
        'city': '',
        'street': '',
        'house_number': '',
        'apartment_number': ''
    })

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('my_profile')  # Redirect после сохранения
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'main/myprofile.html', {'form': form})


def get_user_id(request):
    user_id = None
    if request.user.is_authenticated:
        user_id = request.user.id
    return JsonResponse({'user_id': user_id})

diplom/main/templates/main/about.html
{% extends 'main/index.html' %}


{% block title %}О нас{% endblock title %} 
    

{% block content %}      
      <div class="about">
        <p>Жилой дом в Безенчуке, Самарской области, по адресу ул. Северная, 4 1-этажный,
            имеет общую площадь всех помещений 793.2 квадратных метров.
            <p><span>Административный адрес:</span>
            Самарская область, Район Безенчукский, Поселок городского типа Безенчук,
            Улица Северная, Дом 4 Сокращенный адрес: обл. Самарская, р-н. Безенчукский,
            пгт. Безенчук, ул. Северная, д. 4</p>
        </p>
        <p><span>Муниципальный адрес:</span> Самарская область, Муниципальный район Безенчукский, городское поселение Безенчук, Поселок городского типа Безенчук, Улица Северная, Дом 4
            Сокращенный адрес: обл. Самарская, м.р-н. Безенчукский, г.п. Безенчук, пгт. Безенчук, ул. Северная, д. 4
        </p>
        <p><span>Регион:</span> 63 Самарская обл
            Город / Населенный пункт: Безенчукский р-н, Безенчук пгт
            Улица: Северная ул
            Дом: д. 4
        </p>
        <p> <span>ОКАТО:</span> 36204551000
            <p><span>Индекс:</span> 446250</p>
            <p><span>Реестр:</span> 366041510510000005120005000000000</p>
            <p><span>Кадастр:</span> 63:12:1402001:92</p>
            <p><span>Код ИФНС:</span> 6330</p>
        </p>
        <p> Карточка объекта ФИАС:
            <p><span>Код ФИАС:</span> 113eb3dc-40ff-4f01-98d1-08e0f0372e7d</p>
            <p><span>Код ГАР:</span>  75666290</p>
        </p>
      </div>
{% endblock  %}

diplom/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'main/css/css.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/clock.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/regestration.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://bootstraptema.ru/plugins/2017/thooclock/jquery.thooClock.js"></script>
  
    <title>{% block title %}Главная страница{% endblock %}</title>
    
    {% block css %}{% endblock %}
</head>
<style>
  .navbar-brand{
    padding-left: 170px;
  }
  
  main{
    position: fixed;
    left: 0; right: 0;
    top: 0; bottom: 0;
    z-index: -1;
    background-image: url("../img/mainBG.jpg");
    backdrop-filter: blur(5px);
  }
  footer{
    filter: blur(5px);
  }
  
</style>
<body>
  <header>
        <div class="fixed-top">
            <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
              <div class="container">           
                <div class="navbar-brand">
                  <div class="clock-bottom">
                    <div class="clock">
                      <div id="Date"></div>
                      <ul>
                        <li id="hours"></li>
                        <li id="point">:</li>
                        <li id="min"></li>
                        <li id="point">:</li>
                        <li id="sec"></li>
                      </ul>
                    </div>
                  </div>
                </div>  
              </div>
            </nav>
          </div>
  </header>
      <main>
        {% block content %}{% endblock %}
      </main>    
        
        {% block javascript %}{% endblock %}
  <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Кислинский Сергей Алексеевич &copy; Дипломная работа 2022-2024</p>
        </div>
  </footer>
  <script src="{% static 'main/js/clock.js' %}"></script>
  <script src="{% static 'main/js/nav.js' %}"></script>
</body>

</html>

diplom/main/templates/main/gaz.html
{% extends 'main/index.html' %}
{% load static %}

{% block title %}Газ{% endblock title %}

{% block content %}
    <div class="container conteinr">
        <div class="form-container">
            <div class="left">
                <div class="nomer-scheta">
                    {% comment %} <label for="nomer-input">Номер лицевого счета:</label><br> {% endcomment %}
                    <input id="nomer-input" type="text"
                        placeholder="номер лицевого счета...">
                </div>

                <div class="tarif">
                    {% comment %} <label for="tarif-input">Текущий тариф:</label><br> {% endcomment %}
                    <input id="tarif-input" type="text"
                        placeholder="текущий тариф...">
                </div>

                <div class="porfzaniya">
                    {% comment %} <label for="pokazaniya-input">Показания счетчика:</label><br> {% endcomment %}
                    <input id="pokazaniya-input" type="text"
                        placeholder="показания счетчика..."
                        oninput="calculateSum()">
                </div>
                <br>
                <div class="form-group summa-group">
                    <label for="previous_reading">Предыдущие показания:</label>
                    <div id="previous_reading" class="previous_reading"
                        contenteditable="false">{{ last_meter_reading }}</div>
                    <label class="summa-box-label" for="summa">Сумма к оплате:</label>
                    <div id="summa" class="summa-box"
                        contenteditable="false"></div>
                </div>
                <div class="form-group">
                    {% csrf_token %}
                    <input id="btn" type="submit" value="Сохранить"
                        onclick="saveAndReload()">
                </div>
            </div>
        </div>

        <div class="recent-data uslugi">
            
            <div class="container-pay">
                <h2>Последние показания газа:</h2>
                <input class="btn-pay" id="payButton" value="Оплатить" type="button">
            </div>
            <table>
                <thead>
                <tr>
                    <th>Дата показаний</th>
                    <th>№ счёта</th>
                    <th>Показания</th>
                    <th>Тариф</th>
                    <th>Сумма к оплате</th>
                </tr>
                </thead>
                <tbody id="table-body">
                {% for service in last_12_services %}
                    <tr>
                        <td>{{ service.date }}</td>
                        <td>{{ service.account_number }}</td>
                        <td>{{ service.meter_reading }}</td>
                        <td>{{ service.tariff }}</td>
                        <td id="cost">{{ service.total_cost }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script>
        function calculateSum() {
            const tarif = parseFloat(document.getElementById('tarif-input').value);
            const pokazaniya = parseFloat(document.getElementById('pokazaniya-input').value);
            const previous_reading = {{ last_meter_reading }}; // Получаем показания прошлого периода           
            const button = document.getElementById('btn');
            let summa;

            if (isNaN(tarif) || isNaN(pokazaniya)) {
                summa = NaN;
            } else if (previous_reading === 0.0) {
                summa = tarif * pokazaniya; // Используем другую формулу, если нет предыдущих показаний
            } else if (pokazaniya > previous_reading) {
                summa = tarif * (pokazaniya - previous_reading);
                button.style.display = 'block';
            } else {
                document.getElementById('summa').innerText = 'Нужно сверить показания';
                button.style.display = "none";
            }

            if (isNaN(summa)) {
                document.getElementById('summa').style.color = '#54d400';
                document.getElementById('summa').innerText = 'Нужно сверить показания';
            } else {
                button.style.display = 'block';
                document.getElementById('summa').innerText = summa.toFixed(2);
            }
        }

        function getCSRFToken() {
            return document.querySelector('input[name="csrfmiddlewaretoken"]').value;
        }

        function saveData() {
            const userId = {{ user_id }}; // Получаем user_id из контекста

            const nomerScheta = document.getElementById('nomer-input').value;
            const tarif = parseFloat(document.getElementById('tarif-input').value);
            const pokazaniya = parseFloat(document.getElementById('pokazaniya-input').value);
            const previous_reading = {{ last_meter_reading }}; // Получаем показания прошлого периода
            const summa = tarif * (pokazaniya - previous_reading);
            const utility_type = "{{ utility_type|escapejs }}";

            const formData = new FormData();
            formData.append('account_number', nomerScheta);
            formData.append('tariff', tarif);
            formData.append('meter_reading', pokazaniya);
            formData.append('total_cost', summa);
            formData.append('utility_type', utility_type);
            formData.append('user_id', userId); // Используем userId из контекста

            fetch('/save/', {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': getCSRFToken() // Добавляем CSRF токен в заголовки запроса
                }
            })
                .then(response => {
                    if (response.ok) {
                        console.log('Данные успешно сохранены в базу данных');
                    } else {
                        console.error('Ошибка при сохранении данных в базу данных');
                    }
                })
                .catch(error => {
                    console.error('Произошла ошибка:', error);
                });
        }

        function saveAndReload() {
            saveData(); // Вызываем функцию сохранения данных
            location.reload(); // Перезагружаем страницу
        }

    </script>
{% endblock %}

diplom/main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/css.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/clock.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/uslugi.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/regestration.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/pay.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://bootstraptema.ru/plugins/2017/thooclock/jquery.thooClock.js"></script>
    <script src="https://widget.cloudpayments.ru/bundles/cloudpayments"></script>
 
    <title>{% block title %}Главная страница{% endblock %}</title>
    
    {% block css %}{% endblock %}
</head>

<body>
  <header>
        <div class="fixed-top">
            <nav class="navbar-expand-lg navbar-dark mx-background-top-linear">
              <div class="container">           
                <div class="navbar-brand">
                  <div class="clock-bottom">
                    <div class="clock">
                      <div id="Date"></div>
                      <ul>
                        <li id="hours"></li>
                        <li id="point">:</li>
                        <li id="min"></li>
                        <li id="point">:</li>
                        <li id="sec"></li>
                      </ul>
                    </div>
                  </div>
                </div>  
                <div class="navbar-collapse">
          
                  <ul class="menu-link" id="menu-link">
          
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'index' %}">Домашня</a>
                    </li>
          
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'about' %}">О доме</a>
                    </li>
                    
                    {% if user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'my_profile'%}">Профиль</a>
                      </li>
                    {% else%}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Профиль</a>
                      </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                      </li>
                    {% else%}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Войти</a>
                      </li>
                    {% endif %}

                  </ul>
                </div>
              </div>
            </nav>
          </div>
  </header>
     <aside>
        <ul>
          {% if user.is_authenticated %}
            <a href="{% url 'svet' %}"><li>Свет</li></a>
            <a href="{% url 'gaz' %}"><li>Газ</li></a>
            <a href="{% url 'voda' %}"><li>Вода</li></a>
            <a href="{% url 'chat' %}"><li>Чат</li></a>
          {% else%}
            <a href="{% url 'login' %}"><li>Свет</li></a>
            <a href="{% url 'login' %}"><li>Газ</li></a>
            <a href="{% url 'login' %}"><li>Вода</li></a>
            <a href="{% url 'login' %}"><li>Чат</li></a>
          {% endif %}
        </ul>
      </aside>
      <main>
        {% block content %}
          <div class="index-item">
            {% if user.is_authenticated %}
              <div class="about-zadachi">
                {% include "main/zadachi.html" %}
              </div>
            {% else%}
              <a href="{% url 'login' %}"></a>
            {% endif %}
            <div class="about-pogoda">
              {% include "main/pogoda.html" %}
            </div>
          </div>
        {% endblock %}
      </main>    

  <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Кислинский Сергей Алексеевич &copy; Дипломная работа 2022-2024</p>
        </div>
  </footer>
  <script src="{% static 'main/js/clock.js' %}"></script>
  <script src="{% static 'main/js/nav.js' %}"></script>
  <script src="{% static 'main/js/pay.js' %}"></script>
</body>

</html>

diplom/main/templates/main/myprofile.html
{% extends 'main/index.html' %}
{% load static %}

{% block title %}Профиль{% endblock title %}

{% block content %}
    <div class="container">
        <div class="profile">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="image">
                    {% if form.instance.avatar %}
                        <img class="profile-image" src="{{ form.instance.avatar.url }}" alt="Аватар"><br>
                    {% else %}
                        <img class="profile-image" src="{% static 'main/img/iconUser.png' %}"><br>
                    {% endif %}
                    <input class="file" type="file" name="avatar" id="id_avatar">
                </div>

                <div class="left-item">
                    <div class="item">
                        <label for="id_surname">Фамилия:</label>
                        {{ form.surname }}
                    </div>

                    <div class="item">
                        <label for="id_name">Имя:</label>
                        {{ form.name }}
                    </div>

                    <div class="item">
                        <label for="id_patronymic">Отчество:</label>
                        {{ form.patronymic }}
                    </div>
                </div>
                <div class="right">
                    <div class="right-item">
                        <label for="id_email">Email:</label>
                        {{ form.email }}
                    </div>

                    <div class="right-item">
                        <label for="id_birth_date">Дата рождения:</label>
                        {{ form.birth_date }}
                    </div>

                    <div class="right-item">
                        <label for="id_phone">Телефон:</label>
                        {{ form.phone }}
                    </div>

                    <div class="right-item">
                        <label for="id_city">Город:</label>
                        {{ form.city }}
                    </div>

                    <div class="right-item">
                        <label for="id_street">Улица:</label>
                        {{ form.street }}
                    </div>

                    <div class="right-item">
                        <label for="id_house_number">Номер дома:</label>
                        {{ form.house_number }}
                    </div>

                    <div class="right-item">
                        <label for="id_apartment_number">Номер квартиры:</label>
                        {{ form.apartment_number }}
                    </div>
                </div>
                <button class="profile-btn" type="submit">Сохранить</button>
            </form>

        </div>
    </div>
{% endblock %}